import type { TypesenseCollectionConfig } from "./types.ts";

/** Typesense collection config for out-of-service records. */
export const outOfService: TypesenseCollectionConfig = {
  alias: "out-of-service",
  version: 1,
  firestoreCollection: "out-of-service",
  collectionName: "out-of-service_v1",
  enabled: true,
  schema: {
    name: "out-of-service_v1",
    enable_nested_fields: true,
    fields: [
      { name: "uid", type: "string", sort: true, facet: false },
      { name: "uid_product", type: "string", facet: false },
      { name: "number", type: "int64", sort: true, index: true, facet: false },
      { name: "number_str", type: "string", index: true, sort: false, facet: false, optional: true },
      { name: "reason", type: "string", facet: true },
      { name: "status", type: "string", facet: true },
      { name: "quantity", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown", type: "object" },
      { name: "breakdown.draft", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.planned", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.active", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.blocked", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.written_off", type: "int32", sort: true, index: true, facet: false },
      { name: "breakdown.returned_to_service", type: "int32", sort: true, index: true, facet: false },
      { name: "organization", type: "object", optional: true },
      { name: "organization.uid", type: "string", facet: false, optional: true },
      { name: "organization.name", type: "string", sort: true, stem: true, facet: false, optional: true },
      { name: "dates", type: "object" },
      { name: "dates.start_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "dates.end_fs", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "stores", type: "object[]", optional: true },
      { name: "stores.uid_store", type: "string[]", facet: true, optional: true },
      { name: "stores.name", type: "string[]", stem: true, optional: true },
      { name: "stores.quantity", type: "int32[]", optional: true },
      { name: "query_by_sources", type: "string[]", facet: false, optional: true },
      { name: "canceled_at", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "created_at", type: "int64", sort: true, index: true, facet: false, optional: true },
      { name: "updated_at", type: "int64", sort: true, index: true, facet: false },
    ],
    default_sorting_field: "updated_at",
  },
  synonyms: [],
  displayDefaults: {
    columns: ["number", "reason", "status", "organization.name", "quantity", "dates.start_fs"],
    filters: { status: [] },
    sort: { column: "number", direction: "desc" },
    group: null,
    facet: [],
  },
};
