/**
 * Tests for `it.icons` — the inline-SVG icon helper templates render into PDFs.
 *
 * Two things here are load-bearing rather than cosmetic:
 *
 *  - **Escaping.** `svg()` returns markup, so templates emit it through `<%~ %>`,
 *    which bypasses Eta's auto-escaping. The escaping in `icons.ts` is therefore
 *    the only thing between a caller-supplied `title` and the document.
 *  - **Alias coverage.** The alias map is generated by matching markup; a wrong
 *    entry would point a remembered name at the wrong glyph, and a glyph moves
 *    pixels through the golden gate. The sweep below checks every alias resolves
 *    to a real icon, and that it is not simply an identity mapping.
 */
import { assert, assertEquals, assertStringIncludes, assertThrows } from "@std/assert";
import { CFS_LOGO_SVG, has, svg } from "../src/utils/icons.ts";
import { LUCIDE_ICON_ALIASES, LUCIDE_ICON_DATA } from "../src/utils/_lucide-icons.data.ts";

/** Every canonical name in the packed catalogue. */
function canonicalNames(): string[] {
  return LUCIDE_ICON_DATA.split("\n").map((l) => l.slice(0, l.indexOf("\t")));
}

// ── Rendering ────────────────────────────────────────────────────────

Deno.test("svg renders a known icon with lucide's fixed viewBox and stroke setup", () => {
  const out = svg("truck");
  assertStringIncludes(out, `viewBox="0 0 24 24"`);
  assertStringIncludes(out, `fill="none"`);
  assertStringIncludes(out, `stroke="currentColor"`);
  assertStringIncludes(out, `stroke-linecap="round"`);
  assertStringIncludes(out, `stroke-linejoin="round"`);
  assertStringIncludes(out, `class="lucide lucide-truck"`);
  // The glyph itself, not just a wrapper.
  assertStringIncludes(out, `<circle cx="17" cy="18" r="2"/>`);
  assert(out.startsWith("<svg "), "must be a single inline <svg> element");
  assert(out.endsWith("</svg>"));
});

Deno.test("svg defaults to 16px and stroke-width 2", () => {
  const out = svg("phone");
  assertStringIncludes(out, `width="16"`);
  assertStringIncludes(out, `height="16"`);
  assertStringIncludes(out, `stroke-width="2"`);
});

Deno.test("svg applies size, stroke, color and class", () => {
  const out = svg("truck", { size: 24, stroke: 1.5, color: "#b00", class: "muted inline" });
  assertStringIncludes(out, `width="24"`);
  assertStringIncludes(out, `height="24"`);
  assertStringIncludes(out, `stroke-width="1.5"`);
  assertStringIncludes(out, `stroke="#b00"`);
  assertStringIncludes(out, `class="lucide lucide-truck muted inline"`);
});

Deno.test("svg accepts a string size, so a template can pass em units", () => {
  assertStringIncludes(svg("truck", { size: "1.2em" }), `width="1.2em"`);
});

// ── Accessibility defaults ───────────────────────────────────────────

Deno.test("svg is decorative by default", () => {
  const out = svg("truck");
  assertStringIncludes(out, `aria-hidden="true"`);
  assert(!out.includes("<title>"), "an unnamed icon must not emit a <title>");
});

Deno.test("svg with a title is exposed to assistive tech", () => {
  const out = svg("truck", { title: "Delivery" });
  assertStringIncludes(out, `role="img"`);
  assertStringIncludes(out, `aria-label="Delivery"`);
  assertStringIncludes(out, `<title>Delivery</title>`);
  assert(!out.includes(`aria-hidden`), "a named icon must not also be hidden");
});

// ── Escaping (the security-relevant half) ────────────────────────────

Deno.test("svg escapes a title containing quotes and angle brackets", () => {
  // `<%~` bypasses Eta's auto-escaping, so this is the only escaping there is.
  const out = svg("truck", { title: `Ann"s <script>alert(1)</script> & co` });
  assert(!out.includes("<script>"), "raw markup must not survive into the document");
  assertStringIncludes(out, `aria-label="Ann&quot;s &lt;script&gt;alert(1)&lt;/script&gt; &amp; co"`);
  // Inside element text, quotes need no escaping but the tag must still be inert.
  assertStringIncludes(out, `<title>Ann"s &lt;script&gt;alert(1)&lt;/script&gt; &amp; co</title>`);
});

Deno.test("svg escapes class and color, which land in attribute position", () => {
  const out = svg("truck", { class: `a" onload="x`, color: `b" x="y` });
  // The injected text still appears — inert, because its quotes are escaped, so
  // it never closes the attribute it sits in. That is what to assert: the
  // *unescaped* form is absent, not the substring.
  assert(!/onload="/.test(out), "an injected attribute must not escape its quotes");
  assertStringIncludes(out, `class="lucide lucide-truck a&quot; onload=&quot;x"`);
  assertStringIncludes(out, `stroke="b&quot; x=&quot;y"`);
});

// ── Unknown names ────────────────────────────────────────────────────

Deno.test("svg throws on an unknown icon", () => {
  // Deliberate: a blank icon is invisible in a PDF and would ship, where a throw
  // is caught by the draft render gate and the golden gate first.
  assertThrows(() => svg("definitely-not-an-icon"), Error, "Unknown icon");
});

Deno.test("svg suggests near matches when the name shares a word", () => {
  const err = assertThrows(() => svg("truck-of-holding"), Error);
  assertStringIncludes((err as Error).message, "Did you mean:");
  assertStringIncludes((err as Error).message, "truck");
});

Deno.test("svg still names the docs when there is no near match", () => {
  const err = assertThrows(() => svg("zzzzqqqq"), Error);
  assertStringIncludes((err as Error).message, "lucide.dev/icons");
});

// ── has() ────────────────────────────────────────────────────────────

Deno.test("has agrees with svg over the whole catalogue", () => {
  // A data-driven name is meant to be gated with has(); if the two ever disagree
  // the gate stops protecting the render.
  const names = canonicalNames();
  assertEquals(names.length, 1767);
  const disagreements = names.filter((n) => {
    if (!has(n)) return true;
    try {
      svg(n);
      return false;
    } catch {
      return true;
    }
  });
  assertEquals(disagreements, []);
});

Deno.test("has is false for an unknown name", () => {
  assertEquals(has("definitely-not-an-icon"), false);
});

// ── Aliases ──────────────────────────────────────────────────────────

Deno.test("every alias resolves to a real icon", () => {
  const canonical = new Set(canonicalNames());
  const broken = Object.entries(LUCIDE_ICON_ALIASES)
    .filter(([, to]) => !canonical.has(to));
  assertEquals(broken, []);
  assertEquals(Object.keys(LUCIDE_ICON_ALIASES).length, 258);
});

Deno.test("an alias is never its own canonical, and never shadows one", () => {
  // Either would mean the generator's markup match had collapsed two distinct
  // icons together — the failure mode that puts the wrong glyph in a document.
  const canonical = new Set(canonicalNames());
  for (const [from, to] of Object.entries(LUCIDE_ICON_ALIASES)) {
    assert(from !== to, `alias ${from} maps to itself`);
    assert(!canonical.has(from), `alias ${from} shadows a canonical icon`);
  }
});

Deno.test("svg renders an aliased name under its canonical class", () => {
  // `alert-circle` was renamed to `circle-alert`; an author reaching for the old
  // name gets the icon, classed by what it actually is.
  assertEquals(has("alert-circle"), true);
  assertStringIncludes(svg("alert-circle"), `class="lucide lucide-circle-alert"`);
  assertEquals(svg("alert-circle"), svg("circle-alert"));
});

// ── The logo ─────────────────────────────────────────────────────────

Deno.test("CFS_LOGO_SVG is the five-path logo, inline and self-contained", () => {
  // The preview harness held a ONE-path copy of this (measured 2026-08-13:
  // 5 paths here, 1 there) and rendered a visibly different logo from
  // production. Counting paths is what tells the two apart, so it is the thing
  // worth asserting.
  assertEquals(CFS_LOGO_SVG.match(/<path /g)?.length, 5);
  assertStringIncludes(CFS_LOGO_SVG, `aria-label="Chicago Film Supplies logo"`);
  // Nothing fetchable. `xmlns="http://www.w3.org/2000/svg"` is a namespace
  // IDENTIFIER, not a resource — Chromium never requests it — so the check has
  // to be about fetching verbs, not about the substring "http".
  assert(!/\bhref=|url\(|<image\b/.test(CFS_LOGO_SVG), "the logo must fetch nothing");
});

// ── No external references anywhere in the catalogue ─────────────────

Deno.test("no icon references an external resource", () => {
  // Gotenberg renders with failOnResourceLoadingFailed=true, and header/footer
  // partials load no external resources at all — one `url(...)` or `href` in the
  // catalogue would fail whole documents at render time.
  const offenders = LUCIDE_ICON_DATA.split("\n")
    .filter((l) => /https?:\/\/|url\(|xlink:href|\bhref=/.test(l))
    .map((l) => l.slice(0, l.indexOf("\t")));
  assertEquals(offenders, []);
});
