// AUTO-GENERATED by scripts/generate-template-helpers.ts — do not edit manually.

/** One callable helper in the template editor's helper panel. */
export interface TemplateHelperEntry {
  /** Function name — matches the real `@cfs/core/utils` export. */
  name: string;
  /** Expression as written in a template, e.g. `it.orders.getGroupTotals(items, index, taxes)`. */
  expr: string;
  /** One-line summary, from the function's JSDoc. */
  desc: string;
  /** Rendered TypeScript return type, e.g. `GroupTotalsResult`. */
  returns: string;
}

/**
 * Helper catalogue keyed by utils namespace — `templateHelpers["orders"]` is what
 * a template calls as `it.orders.*`.
 *
 * Generated for every `./utils/*` entrypoint; which of them a given template can
 * actually call is resolved from its collections by `availableUtilNamespaces()`
 * in `./template-context.ts`.
 */
export const templateHelpers: Record<string, TemplateHelperEntry[]> = {
  "allocation": [

  ],
  "bookings": [
    { name: "applyBookingBreakdownDelta", expr: "it.bookings.applyBookingBreakdownDelta(orderBreakdown, prev, next)", desc: "Apply a per-key delta to an order's bookings_breakdown roll-up in place.", returns: "void" },
    { name: "calculateBookingBreakdown", expr: "it.bookings.calculateBookingBreakdown(status, type, quantity, existingBreakdown)", desc: "Project a booking's breakdown for a given **order** status, item type, and total quantity. Pure sync — no I/O.", returns: "indexedAccess" },
    { name: "emptyBookingsBreakdown", expr: "it.bookings.emptyBookingsBreakdown()", desc: "The empty breakdown shape — all seven keys at zero.", returns: "indexedAccess" },
    { name: "isBookingClosed", expr: "it.bookings.isBookingClosed(b)", desc: "Per-booking closure rule.", returns: "boolean" },
    { name: "isOrderBookingsClosed", expr: "it.bookings.isOrderBookingsClosed(bookings)", desc: "Predicate: is the order fully closed?", returns: "boolean" },
    { name: "mergeBookingBreakdown", expr: "it.bookings.mergeBookingBreakdown(current, patch)", desc: "Merge a `Partial<breakdown>` over a current breakdown. Missing keys are inherited from `current`. Useful for the optimistic UI path: a picker types \"returned: 1, out: 2\" and the manager renders the merged result before the API confirms.", returns: "indexedAccess" },
    { name: "sumBookingBreakdown", expr: "it.bookings.sumBookingBreakdown(b)", desc: "Sum the seven values of a single booking's breakdown.", returns: "number" },
    { name: "sumBookingsBreakdown", expr: "it.bookings.sumBookingsBreakdown(bookings)", desc: "Sum a list of booking breakdowns into the order's roll-up shape.", returns: "indexedAccess" },
  ],
  "cards": [
    { name: "computeCardActionFromBookings", expr: "it.cards.computeCardActionFromBookings(side, siblings, current)", desc: "Recompute a card's denormalized **next fulfillment action** from its sibling bookings — the value the `CardTile` button shows on surfaces (Dashboard kanban, Calendar agenda) where no bookings are loaded. Pure function — no Firestore reads. Computed in lockstep with `computeCardStatusFromBookings` on every booking write.", returns: "CardAction | null" },
    { name: "computeCardStatusFromBookings", expr: "it.cards.computeCardStatusFromBookings(side, siblings, current)", desc: "Recompute an event card's `status` from its sibling bookings on the destination it belongs to. Pure function — no Firestore reads.", returns: "CardStatus" },
  ],
  "contact-name": [
    { name: "deriveName", expr: "it.contact-name.deriveName(parts)", desc: "Canonical join rule for deriving a single display string from name parts. Joins `[first_name, middle_name, last_name]` with single spaces (missing parts are dropped, never produce empty padding) and appends ` (pronunciation)` when set. This is the single source of truth — every `name` field on a stored document and `ActorRef.name` is computed by passing through here.", returns: "string" },
  ],
  "dates": [
    { name: "countCfsBusinessDays", expr: "it.dates.countCfsBusinessDays(start, end, holidays)", desc: "Count CFS business days between two dates (excludes weekends and CFS holidays).", returns: "BusinessDaysResult" },
    { name: "formatChargeDays", expr: "it.dates.formatChargeDays(days, unit)", desc: "Format a chargeable days number into display values for a duration input.", returns: "FormatChargeDaysResult" },
    { name: "getDefaultStartDate", expr: "it.dates.getDefaultStartDate(holidays)", desc: "Get the default start date for a rental (next business day at 9am). If after 8am today, defaults to tomorrow. Skips weekends and holidays.", returns: "Date" },
    { name: "getDuration", expr: "it.dates.getDuration(dates, holidays)", desc: "Calculate active and chargeable durations for an order's dates.", returns: "DurationResult" },
    { name: "getEndDateByChargePeriod", expr: "it.dates.getEndDateByChargePeriod(startDate, chargePeriod, holidays)", desc: "Calculate end date based on start date and number of chargeable days. Chargeable days exclude weekends and holidays.", returns: "Date" },
    { name: "isHoliday", expr: "it.dates.isHoliday(testDate, holidays)", desc: "Test if a given date is a CFS holiday.", returns: "boolean" },
    { name: "isOffHours", expr: "it.dates.isOffHours(date)", desc: "Test if a date/time is outside business hours (before 8am or after 4pm).", returns: "boolean" },
    { name: "toChargeDays", expr: "it.dates.toChargeDays(inputValue, isWeeks)", desc: "Convert a duration input value back to chargeable days.", returns: "number" },
    { name: "toChicagoEndOfDay", expr: "it.dates.toChicagoEndOfDay(input)", desc: "Canonicalize to the last representable instant of the Chicago calendar date containing the input (`23:59:59.999` local). The closing twin of {@link toChicagoStartOfDay} — together they turn a pair of dates into the half-open-in-spirit, closed-in-fact window `[startOfDay(s), endOfDay(e)]` that {@link module:stock} overlaps intervals against. Idempotent, DST-aware.", returns: "string" },
    { name: "toChicagoInstant", expr: "it.dates.toChicagoInstant(input)", desc: "Canonicalize any valid ISO datetime string to Chicago offset form, preserving the instant. Idempotent.", returns: "string" },
    { name: "toChicagoStartOfDay", expr: "it.dates.toChicagoStartOfDay(input)", desc: "Canonicalize to Chicago local midnight for the calendar date containing the input instant. Use for fields that semantically represent a date (invoice.date, invoice.due_date, payments[].date). Idempotent.", returns: "string" },
    { name: "toChicagoYmd", expr: "it.dates.toChicagoYmd(input)", desc: "Format an ISO datetime as the Chicago calendar date in `YYYY-MM-DD` form. The inverse of {@link toChicagoStartOfDay} — use to populate `<input type=\"date\">` from a canonical Chicago-offset value.", returns: "string" },
  ],
  "icons": [
    { name: "has", expr: "it.icons.has(name)", desc: "Whether `name` is a known icon (following aliases).", returns: "boolean" },
    { name: "svg", expr: "it.icons.svg(name, arg2)", desc: "Inline SVG markup for a lucide icon. Emit raw: `<%~ it.icons.svg(\"truck\") %>`.", returns: "string" },
  ],
  "invoices": [
    { name: "buildInvoiceDestinationDivider", expr: "it.invoices.buildInvoiceDestinationDivider(source, arg2)", desc: "Build an invoice destination divider from a source order's destination item. Single source of truth for the divider shape — reused by `projectOrderItemToInvoiceItem` (order→invoice projection), the CRMS invoice webhook (`createUpdateInvoiceFromCrms`), and the destination-divider backfill.", returns: "OrderDocDestinationItemType" },
    { name: "calculateInvoiceTotals", expr: "it.invoices.calculateInvoiceTotals(items, taxes, settlements)", desc: "Calculate aggregated pricing totals for an invoice.", returns: "InvoiceTotals" },
    { name: "calculateItemDiscountCents", expr: "it.invoices.calculateItemDiscountCents(item)", desc: "Calculate the discount amount, in cents, for a single line item.", returns: "number" },
    { name: "calculateItemPrice", expr: "it.invoices.calculateItemPrice(item, taxes)", desc: "Calculate the complete price for a single line item. Runs the full pipeline: subtotal → discount → taxes → total.", returns: "typeLiteral" },
    { name: "calculateItemSubtotal", expr: "it.invoices.calculateItemSubtotal(item)", desc: "Calculate the pre-discount and post-discount subtotals for a single line item.", returns: "typeLiteral" },
    { name: "calculateItemTax", expr: "it.invoices.calculateItemTax(item, taxes)", desc: "Calculate tax amounts for a single line item from the Tax[] parameter. Returns a PriceModifier[] with computed amounts.", returns: "PriceModifier[]" },
    { name: "calculateItemTotalCents", expr: "it.invoices.calculateItemTotalCents(item, taxes)", desc: "Calculate the total (subtotal_discounted + taxes) for a single line item.", returns: "number" },
    { name: "derivePaymentStatus", expr: "it.invoices.derivePaymentStatus(currentStatus, amountPaidCents, amountDueCents, arg4)", desc: "Derive invoice status from settlement amounts. Pure function — does not mutate the invoice.", returns: "InvoiceStatusType" },
    { name: "getOrderScopedItems", expr: "it.invoices.getOrderScopedItems(items, orderDividerUid)", desc: "Get all invoice items scoped to a specific order divider. Returns the order divider itself plus all items whose path starts with the order divider's uid.", returns: "T[]" },
    { name: "isPreTaxItem", expr: "it.invoices.isPreTaxItem(item)", desc: "Determine whether a line item participates in subtotal/discount/tax calculations. Standalone predicate (not composed) because TS doesn't support negated predicates.", returns: "item is PreTaxLineItem" },
    { name: "isPriceableItem", expr: "it.invoices.isPriceableItem(item)", desc: "Determine whether a line item is priceable (has a price object, not a structural item).", returns: "item is PriceableLineItem" },
    { name: "isTransactionFeeItem", expr: "it.invoices.isTransactionFeeItem(item)", desc: "Determine whether a line item is a transaction fee.", returns: "item is TransactionFeeLineItem" },
    { name: "toInvoiceDestinationPair", expr: "it.invoices.toInvoiceDestinationPair(uidOrder, pair)", desc: "**The ONE author of an invoice destination pair.** Project an order's pair into the invoice's, tagged with the order it is scoped to.", returns: "InvoiceDestinationPair" },
  ],
  "locations": [
    { name: "normalizeLocationName", expr: "it.locations.normalizeLocationName(name)", desc: "Canonical uniqueness key for a location name, scoped within its store.", returns: "string" },
  ],
  "money": [
    { name: "distributeCents", expr: "it.money.distributeCents(total, parts)", desc: "Split `total` cents into `parts` whole-cent shares that **sum to exactly `total`**.", returns: "bigint[]" },
    { name: "formatCents", expr: "it.money.formatCents(cents, arg2)", desc: "Format integer cents for display **without ever creating a float**.", returns: "string" },
    { name: "formatRate", expr: "it.money.formatRate(value, arg2)", desc: "Render a **rate** for display — {@linkcode formatCents}'s twin at the other boundary, and the direction the rate pair was missing.", returns: "string" },
    { name: "fromCents", expr: "it.money.fromCents(cents)", desc: "Narrow integer cents back to dollars, for a dollar-denominated projection.", returns: "number" },
    { name: "fromCentsBig", expr: "it.money.fromCentsBig(cents)", desc: "The `bigint` flavour of {@linkcode fromCents}.", returns: "number" },
    { name: "parseMoney", expr: "it.money.parseMoney(s)", desc: "Parse a money string to 2dp dollars — the string→money direction.", returns: "number" },
    { name: "parseRate", expr: "it.money.parseRate(s)", desc: "Parse a **rate** string to 4dp — {@linkcode parseMoney}'s twin, and deliberately a separate function rather than a `precision` option.", returns: "number" },
    { name: "perUnitCostAt4dp", expr: "it.money.perUnitCostAt4dp(cents, units)", desc: "A per-unit **rate** in dollars at 4dp — `cents ÷ units`, rounded once.", returns: "number" },
    { name: "roundDivHalfAwayFromZero", expr: "it.money.roundDivHalfAwayFromZero(num, den)", desc: "{@linkcode roundDivHalfUp} for a numerator of **either** sign, rounding half *away from zero*: `1/2 → 1` and `-1/2 → -1`.", returns: "bigint" },
    { name: "roundDivHalfUp", expr: "it.money.roundDivHalfUp(num, den)", desc: "Round `num / den` half-up, exactly, over integers.", returns: "bigint" },
    { name: "toCents", expr: "it.money.toCents(dollars)", desc: "Widen dollars to exact integer cents.", returns: "number" },
    { name: "toCentsBig", expr: "it.money.toCentsBig(dollars)", desc: "The `bigint` flavour of {@linkcode toCents}, for factor arithmetic whose intermediates exceed `Number.MAX_SAFE_INTEGER`.", returns: "bigint" },
  ],
  "movements": [

  ],
  "order-lines": [

  ],
  "orders": [
    { name: "buildPackingList", expr: "it.orders.buildPackingList(items, consolidated, destinationUid)", desc: "Build a packing list from order line items.", returns: "PackingListItem[] | ConsolidatedItem[]" },
    { name: "calculateItemDiscountCents", expr: "it.orders.calculateItemDiscountCents(item)", desc: "Calculate the discount amount, in cents, for a single line item.", returns: "number" },
    { name: "calculateItemPrice", expr: "it.orders.calculateItemPrice(item, taxes)", desc: "Calculate the complete price for a single line item. Runs the full pipeline: subtotal → discount → taxes → total.", returns: "typeLiteral" },
    { name: "calculateItemSubtotal", expr: "it.orders.calculateItemSubtotal(item)", desc: "Calculate the pre-discount and post-discount subtotals for a single line item.", returns: "typeLiteral" },
    { name: "calculateItemTax", expr: "it.orders.calculateItemTax(item, taxes)", desc: "Calculate tax amounts for a single line item from the Tax[] parameter. Returns a PriceModifier[] with computed amounts.", returns: "PriceModifier[]" },
    { name: "calculateItemTotalCents", expr: "it.orders.calculateItemTotalCents(item, taxes)", desc: "Calculate the total (subtotal_discounted + taxes) for a single line item.", returns: "number" },
    { name: "calculateOrderTotals", expr: "it.orders.calculateOrderTotals(items, taxes)", desc: "Calculate aggregated pricing totals for an entire order. Owns the two-pass computation: pre-tax items first, then transaction fees.", returns: "OrderTotals" },
    { name: "calculateReplacementTotals", expr: "it.orders.calculateReplacementTotals(items, taxes)", desc: "Calculate the total replacement cost across all pre-tax items that have a replacement value on their price object.", returns: "ReplacementTotals" },
    { name: "consolidateItems", expr: "it.orders.consolidateItems(lineItems)", desc: "Deduplicate line items by product UID and sum quantities.", returns: "ConsolidatedItem[]" },
    { name: "getDefaultChargeDays", expr: "it.orders.getDefaultChargeDays(dates, holidays)", desc: "Compute default chargeable days from order dates and holidays. Returns null if required dates are missing.", returns: "number | null" },
    { name: "getDestinationPairItemName", expr: "it.orders.getDestinationPairItemName(destination, index)", desc: "Build a display name for a destination pair from its delivery/collection addresses. Falls back to \"Destination N\" when no addresses are present.", returns: "string" },
    { name: "getDestinationsLegend", expr: "it.orders.getDestinationsLegend(destinations)", desc: "Pair-derived legend strings for the order's start/end dates.", returns: "typeLiteral" },
    { name: "getGroupItems", expr: "it.orders.getGroupItems(items, index)", desc: "Collect the child product items belonging to a collapsible section.", returns: "LineItem[]" },
    { name: "getGroupPath", expr: "it.orders.getGroupPath(items, index)", desc: "Walk backwards from `index` to determine which destination and group an item belongs to. `destination` is the destination's `uid_delivery`; `group` is the group item's `uid` (not its display name) — keying on uid lets group display names be edited without losing collapse state or risking collisions between two groups that happen to share a name.", returns: "GroupPath" },
    { name: "getGroupTotals", expr: "it.orders.getGroupTotals(items, index, taxes)", desc: "Get count and pricing totals for a collapsed section.", returns: "GroupTotalsResult" },
    { name: "getTaxTotals", expr: "it.orders.getTaxTotals(items, taxes)", desc: "Aggregate tax PriceModifiers by name across all pre-tax items.", returns: "PriceModifier[]" },
    { name: "getTotalDiscountCents", expr: "it.orders.getTotalDiscountCents(items)", desc: "Calculate the total discount amount, in cents, across all pre-tax items.", returns: "number" },
    { name: "getTransactionFeeTotals", expr: "it.orders.getTransactionFeeTotals(items)", desc: "Aggregate priced fee lines into the document-level `transaction_fees` rollup.", returns: "PriceModifier[]" },
    { name: "groupByDestination", expr: "it.orders.groupByDestination(items, fallbackDeliveryUid, fallbackCollectionUid)", desc: "Slice the flat items array into destination sections.", returns: "DestinationGroup[]" },
    { name: "isPreTaxItem", expr: "it.orders.isPreTaxItem(item)", desc: "Determine whether a line item participates in subtotal/discount/tax calculations. Standalone predicate (not composed) because TS doesn't support negated predicates.", returns: "item is PreTaxLineItem" },
    { name: "isPriceableItem", expr: "it.orders.isPriceableItem(item)", desc: "Determine whether a line item is priceable (has a price object, not a structural item).", returns: "item is PriceableLineItem" },
    { name: "isSameAsDeliveryDates", expr: "it.orders.isSameAsDeliveryDates(dates)", desc: "Whether charge dates match the delivery/collection dates (i.e. no custom charge period has been set).", returns: "boolean" },
    { name: "isSameAsDeliveryDestination", expr: "it.orders.isSameAsDeliveryDestination(destination)", desc: "Whether a destination's collection endpoint matches its delivery endpoint (address, contact, and instructions are all equal).", returns: "boolean" },
    { name: "isTaxableCoa", expr: "it.orders.isTaxableCoa(coaRevenue)", desc: "Is a line with this revenue COA subject to tax?", returns: "boolean" },
    { name: "isTransactionFeeItem", expr: "it.orders.isTransactionFeeItem(item)", desc: "Determine whether a line item is a transaction fee.", returns: "item is TransactionFeeLineItem" },
    { name: "orderHasDiscount", expr: "it.orders.orderHasDiscount(items)", desc: "Check whether any pre-tax line item has a discount.", returns: "boolean" },
    { name: "orderHasRentals", expr: "it.orders.orderHasRentals(items)", desc: "Check whether any line item is a rental.", returns: "boolean" },
    { name: "orderHasTax", expr: "it.orders.orderHasTax(items)", desc: "Check whether any pre-tax line item has taxes applied.", returns: "boolean" },
  ],
  "organizations": [

  ],
  "products": [
    { name: "buildComponentEntries", expr: "it.products.buildComponentEntries(parentUid, sourceComponents, baseDepth, maxDepth)", desc: "Build component entries for a parent product from a component product's own `components` array. Each entry's `path` is prepended with `parentUid` so it reflects its position in the parent's tree.", returns: "T[]" },
    { name: "removeComponentEntries", expr: "it.products.removeComponentEntries(components, path)", desc: "Remove a component and all its descendants from a flat components array. An entry is removed if its `path` starts with the given path prefix — this covers the component itself and every entry nested beneath it.", returns: "T[]" },
  ],
  "stock": [

  ],
  "taxes": [
    { name: "assertCoaTaxMapCoversCore", expr: "it.taxes.assertCoaTaxMapCoversCore()", desc: "Fail closed if the taxable-COA set has grown past {@link TAXABLE_COA_TO_TAX_NAME}.", returns: "void" },
    { name: "assignLineTaxes", expr: "it.taxes.assignLineTaxes(items, ctx)", desc: "**Write the rule's answer onto every priceable line** — `price.taxes`, `price.taxes_base` and a refreshed `price.total_cents`. Mutates in place; computes no subtotal.", returns: "void" },
    { name: "defaultTaxNameForLine", expr: "it.taxes.defaultTaxNameForLine(coaRevenue, type)", desc: "**The one default-tax rule**: the tax NAME a newly authored line should carry, given its account and its type.", returns: "string | null" },
    { name: "deriveJurisdiction", expr: "it.taxes.deriveJurisdiction(address, origin)", desc: "**Where a delivery address sources to** — the bottom of the three-level jurisdiction precedence ({@link resolveJurisdiction}), below the document's own destination entry and the organization's `jurisdiction_claim`.", returns: "JurisdictionType" },
    { name: "deriveOrderTaxAsOf", expr: "it.taxes.deriveOrderTaxAsOf(destinations, now)", desc: "As-of instant for resolving an order's taxes: the earliest destination delivery start, falling back to `now`.", returns: "string" },
    { name: "destinationJurisdictions", expr: "it.taxes.destinationJurisdictions(ctx)", desc: "**The jurisdiction each of a document's destinations resolves to**, with the level that answered — one entry per `destinations[]` entry, in document order.", returns: "ResolvedJurisdiction[]" },
    { name: "destinationsForItems", expr: "it.taxes.destinationsForItems(items, destinations)", desc: "The `destinations[]` entry each item is billed under — **one array, parallel to `items`**, so the caller walks the document once rather than per line.", returns: "Array<TaxDestination | null>" },
    { name: "findTaxAt", expr: "it.taxes.findTaxAt(taxes, name, asOf)", desc: "Pick the Tax whose applied window contains `asOf`, matched by exact `name`. Returns null when nothing matches (e.g. `asOf` before any historical doc). Throws on catalog drift (two same-name docs bracket the same instant).", returns: "Tax | null" },
    { name: "findTaxFor", expr: "it.taxes.findTaxFor(taxes, jurisdiction, itemType, asOf)", desc: "**The tax rule: `(jurisdiction × item type)`, as of a date.**", returns: "Tax | null" },
    { name: "isTaxableCoa", expr: "it.taxes.isTaxableCoa(coaRevenue)", desc: "Is a line with this revenue COA subject to tax?", returns: "boolean" },
    { name: "resolveJurisdiction", expr: "it.taxes.resolveJurisdiction(levels)", desc: "**Resolve which jurisdiction a destination's lines are taxed in.** The one implementation of the precedence — per DESTINATION, never per document, which is what lets one order carry two jurisdictions.", returns: "ResolvedJurisdiction" },
    { name: "resolveLineTax", expr: "it.taxes.resolveLineTax(item, destination, ctx)", desc: "**The pricing rule, for one line.** Tax liability is `(item type × jurisdiction)`, resolved per line through its own destination.", returns: "LineTaxResolution" },
  ],
  "templates": [
    { name: "bumpSemver", expr: "it.templates.bumpSemver(current, bump)", desc: "Apply a bump level to a `MAJOR.MINOR.PATCH` semver string. A missing/invalid `current` is treated as `0.0.0` (so the first publish off `deriveBump` yields `1.0.0` for a major, `0.1.0` for a minor, `0.0.1` for a patch).", returns: "string" },
    { name: "deriveBump", expr: "it.templates.deriveBump(type, breaking)", desc: "Map a conventional-commit type + breaking flag to a semver bump level. Breaking always wins (`major`). `feat` → `minor`. Everything else (`fix`, `refactor`, `chore`, `docs`, …) → `patch`.", returns: "BumpLevel" },
    { name: "fixtureDir", expr: "it.templates.fixtureDir(gitPath)", desc: "Directory holding a template family's fixtures: `fixtures/<git_path>/`.", returns: "string" },
    { name: "fixturePath", expr: "it.templates.fixturePath(gitPath, slug)", desc: "Path to one fixture: `fixtures/<git_path>/<slug>.json`.", returns: "string" },
    { name: "goldenPath", expr: "it.templates.goldenPath(branch, gitPath, slug)", desc: "Path to one branch-keyed golden: `goldens/<branch>/<git_path>/<slug>.png`.", returns: "string" },
    { name: "hashTemplateContent", expr: "it.templates.hashTemplateContent(content)", desc: "Order-independent fingerprint of a template/component content map (path → file text). The API stamps a version's `committed_content_hash` with this when it pushes content to git (commit / release); the manager hashes the live draft content the same way to detect \"dirty since last commit\" and warn at approve-to-merge.", returns: "string" },
    { name: "parseFixturePath", expr: "it.templates.parseFixturePath(path)", desc: "Parse a fixture path back to `{ gitPath, slug }`. Returns `null` for any path that isn't of the form `fixtures/<gp>/<slug>.json`. The affected-set classifier consumes this to route fixture-only PR changes into the `goldenOnly` bucket (golden re-run, no version bump).", returns: "typeLiteral | null" },
    { name: "resolveRenderParams", expr: "it.templates.resolveRenderParams(declared, provided)", desc: "Resolve caller-provided render params against a version's declared params, **strictly**: - any provided key not declared → throw `RenderParamError`; - a provided value of the wrong type → throw; - a declared param absent from input → its `default` (or `false` for a boolean with no default), unless `required` with no default → throw.", returns: "Record<string, boolean>" },
    { name: "rewriteDocFieldRefs", expr: "it.templates.rewriteDocFieldRefs(content, fieldMap)", desc: "Rewrite `it.doc.<from>` → `it.doc.<to>` across a content map per `fieldMap` (normalized paths from `scanDocFieldRefs`). Entries mapped to `null` (or to themselves) are left untouched — the operator resolves those by hand. Array indices are preserved (`items[0].name` with map `items[].name`→`lines[].name` becomes `lines[0].name`). Longest `from` rewritten first so a nested path is handled before its prefix.", returns: "Record<string, string>" },
    { name: "scanDocFieldRefs", expr: "it.templates.scanDocFieldRefs(content)", desc: "Distinct `it.doc.<path>` references across a content map, with array indices normalized (`it.doc.items[0].name` → `items[].name`) so paths match the `templateSchemaFields` catalog. Sorted, deduped.", returns: "string[]" },
    { name: "slugify", expr: "it.templates.slugify(name)", desc: "Derive a URL/git-safe slug from a display name. Lowercases, replaces every run of non-alphanumeric characters with a single hyphen, and trims leading/ trailing hyphens. Two distinct display names can collapse to the same slug (e.g. \"Quote!\" and \"quote\") — callers enforce slug uniqueness at create.", returns: "string" },
  ],
};
