/**
 * Generates static template schema field metadata from Zod schemas.
 *
 * Walks every template source + target collection schema and outputs a typed
 * `Partial<Record<collection, SchemaField[]>>` to
 * src/schemas/template-schema-fields.generated.ts — committed, not gitignored.
 *
 * The walk itself lives in `./schema-walk.ts`, so the tests can exercise the
 * exact code path that produced the committed output (see the synthetic PII test
 * in tests/schema-fields.test.ts). That module's doc explains the engine
 * (`z.toJSONSchema()`) and the three markers it carries across.
 *
 * Run: deno task generate-schema-template-fields
 *
 * Pass `--stdout` to print the file instead of writing it. That mode is what
 * `deno task check:generated` diffs against the committed copy, so the
 * staleness gate never has to write into `src/` to prove the file is current.
 */
import { TEMPLATE_SOURCE_COLLECTIONS, TEMPLATE_TARGET_COLLECTIONS } from "../src/schemas/template.ts";
import { templateSchemaFor } from "../src/schemas/template-schemas.ts";
import type { TemplateCollectionType } from "../src/schemas/template-context.ts";
import { type SchemaField, walkSchema } from "./schema-walk.ts";

/**
 * Every collection a template can read from or produce, paired with its schema.
 *
 * Collections with no schema are simply absent from the output — no skip branch
 * or error needed, and the generated type is `Partial` to match. Targets reuse
 * the exact same PII-omission + field-hiding walk as sources: a target's fields
 * are an output shape, but a `redact` path must never surface either way.
 *
 * 🔴 **The lookup is {@link templateSchemaFor}, NOT `isCollectionName`.** It was
 * the latter until api-cloudrun#700, which made "has a walkable schema" and "is
 * a Firestore collection" the same question. They are not: `movement-sessions`
 * is a source with a real schema and no collection, and under the old filter it
 * would have been dropped **silently** — the direction that reports clean.
 * `tests/schema-fields.test.ts` asserts every SOURCE survives, so the drop is
 * now a failure rather than an empty panel.
 */
const COLLECTIONS: TemplateCollectionType[] = [
  ...new Set<TemplateCollectionType>([
    ...TEMPLATE_SOURCE_COLLECTIONS,
    ...TEMPLATE_TARGET_COLLECTIONS,
  ]),
].filter((collection) => templateSchemaFor(collection) !== undefined);

/**
 * Render the whole generated module as a string.
 *
 * Exported and pure — no I/O — so `tests/schema-fields.test.ts` can assert the
 * committed file is current by calling this directly. That matters beyond
 * tidiness: the staleness test used to SPAWN this script, and a spawned child
 * carries its own permissions, so it rewrote `src/` on every green run no
 * matter what the test process was allowed to do. Comparing against a return
 * value removes the write entirely rather than restricting it.
 */
export function renderTemplateSchemaFields(): string {
  const entries: string[] = [];

  for (const collection of COLLECTIONS) {
    // Non-null: `COLLECTIONS` is exactly the members this lookup answers for.
    const fields: SchemaField[] = walkSchema(templateSchemaFor(collection)!);

    const fieldLines = fields
      .map((f) => `    { path: ${JSON.stringify(f.path)}, type: ${JSON.stringify(f.type)} },`)
      .join("\n");
    entries.push(`  ${JSON.stringify(collection)}: [\n${fieldLines}\n  ]`);
  }

  return `// AUTO-GENERATED by scripts/generate-schema-template-fields.ts — do not edit manually.
import type { TemplateSourceCollectionType, TemplateTargetCollectionType } from "./template.ts";

/** A single field entry in the schema reference. */
export interface SchemaField {
  path: string;
  type: string;
}

/**
 * Pre-compiled document field metadata for every template source and target
 * collection. Source collections are always present; a target is present only if
 * it has a walkable schema — \`packing_lists\` has none, hence \`Partial\`.
 */
export const templateSchemaFields: Partial<
  Record<TemplateSourceCollectionType | TemplateTargetCollectionType, SchemaField[]>
> = {
${entries.join(",\n")},
};
`;
}

if (import.meta.main) {
  const output = renderTemplateSchemaFields();

  if (Deno.args.includes("--stdout")) {
    // Bare stdout, so the caller can pipe it straight into `diff` — hence no
    // summary line in this arm.
    await Deno.stdout.write(new TextEncoder().encode(output));
  } else {
    const outPath = new URL("../src/schemas/template-schema-fields.generated.ts", import.meta.url);
    await Deno.writeTextFile(outPath, output);
    console.log(`Wrote ${outPath.pathname} (${COLLECTIONS.length} collections: ${COLLECTIONS.join(", ")})`);
  }
}
