/**
 * Generates static template schema field metadata from Zod schemas.
 *
 * Walks every template source + target collection schema and outputs a typed
 * `Partial<Record<collection, SchemaField[]>>` to
 * src/schemas/template-schema-fields.generated.ts — committed, not gitignored.
 *
 * The walk itself lives in `./schema-walk.ts`, so the tests can exercise the
 * exact code path that produced the committed output (see the synthetic PII test
 * in tests/schema-fields.test.ts). That module's doc explains the engine
 * (`z.toJSONSchema()`) and the three markers it carries across.
 *
 * Run: deno task generate-schema-template-fields
 */
import { isCollectionName, schemaFor } from "../src/schemas/mod.ts";
import { TEMPLATE_SOURCE_COLLECTIONS, TEMPLATE_TARGET_COLLECTIONS } from "../src/schemas/template.ts";
import { type SchemaField, walkSchema } from "./schema-walk.ts";

/**
 * Every collection a template can read from or produce.
 *
 * Filtered to those with a walkable schema in the `schemas` map: `packing_lists`
 * has none, so it is simply absent from the output — no skip branch or error
 * needed, and the generated type is `Partial` to match. Targets reuse the exact
 * same PII-omission + field-hiding walk as sources: a target's fields are an
 * output shape, but a `redact` path must never surface either way.
 *
 * ⚠️ **The filter is {@link isCollectionName}, so it NARROWS.** It used to be
 * `(collection) => schemas[collection]` — the same runtime check, indexing a
 * mapped type by a `string`, which is an implicit `any` (TS7053) and left
 * `walkSchema` taking an unchecked argument. Same guard, now paying for itself
 * at compile time, which is what that helper exists for.
 */
const COLLECTIONS = [
  ...new Set<string>([...TEMPLATE_SOURCE_COLLECTIONS, ...TEMPLATE_TARGET_COLLECTIONS]),
].filter(isCollectionName);

const entries: string[] = [];

for (const collection of COLLECTIONS) {
  const fields: SchemaField[] = walkSchema(schemaFor(collection));

  const fieldLines = fields
    .map((f) => `    { path: ${JSON.stringify(f.path)}, type: ${JSON.stringify(f.type)} },`)
    .join("\n");
  entries.push(`  ${JSON.stringify(collection)}: [\n${fieldLines}\n  ]`);
}

const output = `// AUTO-GENERATED by scripts/generate-schema-template-fields.ts — do not edit manually.
import type { TemplateSourceCollectionType, TemplateTargetCollectionType } from "./template.ts";

/** A single field entry in the schema reference. */
export interface SchemaField {
  path: string;
  type: string;
}

/**
 * Pre-compiled document field metadata for every template source and target
 * collection. Source collections are always present; a target is present only if
 * it has a walkable schema — \`packing_lists\` has none, hence \`Partial\`.
 */
export const templateSchemaFields: Partial<
  Record<TemplateSourceCollectionType | TemplateTargetCollectionType, SchemaField[]>
> = {
${entries.join(",\n")},
};
`;

const outPath = new URL("../src/schemas/template-schema-fields.generated.ts", import.meta.url);
await Deno.writeTextFile(outPath, output);
console.log(`Wrote ${outPath.pathname} (${COLLECTIONS.length} collections: ${COLLECTIONS.join(", ")})`);
